language: node_js
sudo: false
# dist: trusty
# addons:
#   chrome: stable
cache: yarn

node_js:
- '10'

# before_install:
#   - # start your web application and listen on `localhost`
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script: 
- yarn build:static
#- yarn build:optimize-css
- mkdir -p dist_html
- mv dist/*.html dist_html

before_deploy:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: web.silke.design
    region: $AWS_DEFAULT_REGION
    local-dir: dist_html
    skip_cleanup: true
    acl: bucket_owner_full_control
    cache_control: "s-maxage=31536000"
    default_text_charset: 'utf-8'
    on:
      repo: digitalkaoz/silke.design
      branch: master

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: web.silke.design
    region: $AWS_DEFAULT_REGION
    local-dir: dist
    skip_cleanup: true
    acl: bucket_owner_full_control
    cache_control: "max-age=31536000"
    default_text_charset: 'utf-8'
    on:
      repo: digitalkaoz/silke.design
      branch: master

after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
